CREATE UNIQUE INDEX idx_oid ON iql_data (oid);
CREATE INDEX idx_dip ON iql_data (dip);
CREATE INDEX idx_full_path ON iql_data (full_path);
CREATE INDEX idx_name ON iql_data (name);
CREATE INDEX idx_name_val_n ON iql_data (name, val_n);
CREATE INDEX idx_name_val_s ON iql_data (name, val_s);
CREATE INDEX idx_path_id ON iql_data (path_id);
CREATE INDEX idx_path_nodes ON iql_data USING gin(path_nodes);
CREATE INDEX idx_sip ON iql_data (sip);
CREATE INDEX idx_time_from ON iql_data (time_from);
CREATE INDEX idx_time_to ON iql_data (time_to);
CREATE INDEX idx_val_a_n ON iql_data (val_a_n);
CREATE INDEX idx_val_a_s ON iql_data (val_a_s);
CREATE INDEX idx_val_n ON iql_data (val_n);
CREATE INDEX idx_val_s ON iql_data (val_s);
