DROP TABLE IF EXISTS query_queue;

CREATE TABLE query_queue(
  ID VARCHAR(255) NOT NULL,
  IQL TEXT NOT NULL,
  SQL_QUERY TEXT NOT NULL,
  RESULT TEXT,
  STATE VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX idx_query_id ON query_queue (id);
